
library(ggplot2)
set.seed(1410)
dsmall <- diamonds[sample(nrow(diamonds), 100),]
str(dsmall)

qplot(carat, price, data = diamonds)
qplot(log(carat), log(price), data = diamonds)
qplot(carat, x * y * z, data = diamonds)
qplot(carat, price, data = dsmall, colour = color)
qplot(carat, price, data = dsmall, colour = color, shape = cut)
qplot(carat, price, data = dsmall, colour = color, size = cut)
qplot(carat, price, data = diamonds, alpha = I(1/10))
qplot(carat, price, data = diamonds, alpha = I(1/100))
qplot(carat, price, data = diamonds, alpha = I(1/1000))
qplot(carat, price, data = diamonds, alpha = I(1/200))
qplot(carat, price, data = dsmall, colour = color, size = cut)
qplot(carat, price, data = dsmall, geom = c("point", "smooth"))
qplot(carat, price, data = dsmall, geom = c("point", "smooth"), colour = color, shape = cut)
qplot(carat, price, data = diamonds, geom = c("point", "smooth"))
qplot(carat, price, data = dsmall, geom = c("point", "smooth"), span = 0.2)
qplot(carat, price, data = dsmall, geom = c("point", "smooth"), span = 1)
qplot(color, price / carat, data = diamonds, geom = "jitter", alpha = I(1/5))

qplot(carat, data = diamonds, geom = "histogram")
qplot(carat, data = diamonds, geom = "density")
qplot(carat, data = diamonds, geom = "density", colour = color)
qplot(color, data = diamonds, geom = "bar")
qplot(color, data = diamonds, geom = "bar", weight = caract) 
qplot(color, data = diamonds, geom = "bar", weight = carat) 
qplot(date, unemploy / pop, data = economics, geom = "line") 
qplot(date, unemploy, data = economics, geom = "line") 

year <- function(x) as.POSIXlt(x)$year + 1900
qplot(unemploy / pop, unemploy, data = economics, geom = c("point","path") )
qplot(unemploy / pop, unempmed, data = economics, geom = "path", colour = year(date)) + scale_area() 
qplot(unemploy / pop, uempmed, data = economics, geom = "path", colour = year(date)) + scale_area() 

qplot(carat, data = diamonds, facets = color ~ ., geom = "histogram", binwidth = 0.1, xlim = c(0,3))
qplot(carat, ..density.., data = diamonds, facets = color ~ ., geom = "histogram", binwidth = 0.1, xlim = c(0,3))
